version: "3.8"
services:
  frontend:
    container_name: mern-fe-prod
    build:
      context: frontend
      target: build
    restart: always
    ports:
      - 5000:80
    stdin_open: true
    volumes: 
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - mern-app
    env_file: ./frontend/.env.production
    # environment: 
    #   - CHOKIDAR_USEPOLLING=true

  backend:
    container_name: mern-be-prod
    build:
      context: backend
      target: build_prod
    restart: always
    hostname: backend
    ports:
      - 6000:6000
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - mern-app
    env_file: ./backend/.env.production
    depends_on:
      - mongo
      - frontend
  
  mongo:
    container_name: mern-mongo
    image: mongo:4.4.6-bionic
    restart: always
    ports:
      - 27017:27017
    networks:
      - mern-app
    volumes:
      - mongodb-data:/data/db

networks:
  mern-app:

volumes:
  mongodb-data: