version: "3.8"
services:
  frontend:
    container_name: mern-fe-prod
    build:
      context: frontend
      target: build_prod
    restart: always
    hostname: frontend
    ports:
      - 3000:3000
    stdin_open: true
    volumes: 
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - mern-app
    env_file: ./frontend/.env.production
    environment: 
      - CHOKIDAR_USEPOLLING=true
    depends_on: 
      - backend

  backend:
    container_name: mern-be-prod
    build:
      context: backend
      target: build_prod
    restart: always
    hostname: backend
    ports:
      - 8081:8081
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - mern-app
    depends_on:
      - mongo
  
  mongo:
    container_name: mern-mongo-prod
    image: mongo:4.4.6-bionic
    restart: always
    ports:
      - 27017:27017
    networks:
      - mern-app
    volumes:
      - mongodb-data:/data/db

  nginx:
    container_name: mern-nginx-prod
    build:
      context: nginx
    restart: always
    networks:
      - mern-app
    ports: 
      - 80:80

networks:
  mern-app:

volumes:
  mongodb-data: